name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 via SSH for Cleanup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Connected to EC2 for setup"

            # Check if Node.js is already installed
            if ! command -v node &> /dev/null; then
                echo "Node.js not found. Installing..."
                # Install Node.js using the NodeSource repository
                curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
                sudo yum install -y nodejs
            else
                echo "Node.js is already installed. Version: $(node -v)"
            fi

            echo "Node.js installation completed"

  clone_repo:
    runs-on: ubuntu-latest
    needs: cleanup

    steps:
      - name: Connect to EC2 via SSH to Clone Repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Connected to EC2 for setup"

            # Install Git if not already installed
            if ! command -v git &> /dev/null
            then
                echo "Git not found. Installing..."
                sudo yum install -y git  # Use `sudo apt-get install -y git` for Ubuntu
            fi

            # Ensure the repository directory exists, clone if not
            if [ ! -d "auction-service" ]; then
              echo "Directory does not exist. Cloning repository..."
              # Use the GitHub SSH key to pull the latest code
              echo "${{ secrets.TMS_GITHUB_SSHKEY }}" > ~/.ssh/tms_github_id_rsa
              chmod 600 ~/.ssh/tms_github_id_rsa
              eval $(ssh-agent)
              ssh-add ~/.ssh/tms_github_id_rsa
              git clone https://github.com/exagonsoft/auction-service.git
            else
              echo "Directory exists. No need to clone."
            fi

            # Navigate to the repository directory
            cd auction-service

            # Use the GitHub SSH key to pull the latest code
            echo "${{ secrets.TMS_GITHUB_SSHKEY }}" > ~/.ssh/tms_github_id_rsa
            chmod 600 ~/.ssh/tms_github_id_rsa
            eval $(ssh-agent)
            ssh-add ~/.ssh/tms_github_id_rsa

            git fetch origin master
            git reset --hard origin/master
            echo "GitHub Repo Updated"

            rm ~/.ssh/tms_github_id_rsa
            echo "Setup completed"

  deploy:
    runs-on: ubuntu-latest
    needs: clone_repo

    steps:
      - name: Connect to EC2 via SSH to Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Connected to EC2 for deployment"

            cd auction-service

            rm .env
            echo "MONGO_URI=${{ vars.MONGO_URI }}" >> .env
            echo "JWT_SECRET=${{ vars.JWT_SECRET }}" >> .env
            echo "APP_PORT=${{ vars.APP_PORT }}" >> .env

            echo "Env file Created"

            sudo npm install
            sudo npm start

            echo "CI/CD finished Success"
